### PR TITLE
Update binarySearch.js

### PR DESCRIPTION
**Pull request by wrass**
Speed increase using bitwise shift for array length shorter than 32bit threshold (avoiding function overhead from Math.floor)

### CODE REVIEW

**Comment by Olical** [comment]
Hm, the tests take basically the same amount of time. Should we benchmark this at all maybe? Do you have any? Thanks for the input though! :)

(the tests still pass, it just doesn't seem faster)

**Comment by wrass** [comment]
The only testing I did for this was with your gulp-bench test suite which showed a speed improvement of around 2-2.5 times on an old Dell laptop earlier today.  I'll set up a jsperf test case if I get time over the weekend but using a direct bitwise shift in place of the division and Math.floor call will be significantly quicker, for example:
https://jsperf.com/jsfvsbitnot/2
https://jsperf.com/floor-performance/2

The bitwise test is a fallback to deal with arrays over 2^31-1 in length as bitwise operands are all 32-bit signed integers in JS.

Hope it helps.

**Comment by wrass** [comment]
Test cases here for this change: http://jsperf.com/bitwise-shift-vs-division-and-floor-in-binary-search

The improvement appears to be marginal but consistent on JSPerf.

**Comment by Olical** [comment]
Oh that's excellent! Great job on the test, the difference is huge for me (Intel i7, Linux, Firefox and Chrome), I'm happy to merge this since all of the generative tests pass and the benchmark looks excellent.

**Comment by wrass** [comment]
No problem, happy to help.

**Pull request merged**
