### PR TITLE
Simplify code by eliminating duplicate logic

### PR DESCRIPTION
**Pull request by kworth**
Two options here. Commit 1 and commit 2.

After moving the bitwise check into the while loop (in commit 1), I started to guess the reason you didn't do this in the first place is presumably for the sake of run-time performance.

Therefore in commit 2 I attempted to eliminate the repeated if check, but now my new presumption is that the passing of variables into a function will be seen as a run-time performance hit.

Oh well, I've already gone through the trouble of writing/committing the code. So I might as well create the pull request in case you want it. Cheers.

### CODE REVIEW

**Comment by Olical** [comment]
Hey @kworth. That change was made by @wrass (https://github.com/Olical/binary-search/pull/2) for the sake of performance, yes. He benchmarked it too which ended up being pretty impressive. If you can reduce duplication without hindering performance then that's ideal :)

Would you like to add it to @wrass' jsperf tests for comparison?

**Comment by kworth** [comment]
I (very quickly) looked at the tests. I did not take the time to figure out how to run them. I thought I saw only functional tests. Where are the performance tests and how do I run them?

**Comment by Olical** [comment]
They were referenced in the previous PR, they're on [jsperf](http://jsperf.com/bitwise-shift-vs-division-and-floor-in-binary-search) :)

**Comment by wrass** [comment]
Just to clarify, any conditional logic or function call within the main while loop is going to add a processing overhead that scales with the number of guesses, hence I added the extra while in #2 to keep the necessary decision on whether to use a bitwise operator out of the loop.  Admittedly it reduces readability, but it's a tiny space-time tradeoff for increased speed.

**Comment by Olical** [comment]
Yep, that's why I think if this change is benchmarked we'll see it slow down. Some binary search implementations in other languages look horrific for the sake of speed and efficiency. But that's okay.

**Comment by kworth** [comment]
Indeed. I made some additions to the jsperf mentioned. Yikes! Way worse than I ever would have thought. Very educational. But let's not allow this to drive us into an anti-pattern!

**Comment by Olical** [comment]
The only reason we sacrifice beauty of code for performance here is because binary search is typically used at the heart of a very tight loop of algorithm designed to work on a lot of data. A minor slow down here means a huge slowdown for the thing using it. Potentially changing minutes to days of running time.

Thanks for the PR though! All discussion and suggestions are greatly appreciated. I hope you find this useful.

**Pull request closed without merging**
